name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    
    - name: Run tests and generate coverage
      run: |
        pytest --cov=. --cov-report=term --cov-report=json:coverage.json

    - name: Update Coverage Badge
      if: github.ref == github.event.repository.default_branch
      uses: we-cli/coverage-badge-action@main
      with:
        files: ./coverage.json

      
